did some naive test

diff --git a/vivado-wrapper b/vivado-wrapper
--- a/vivado-wrapper
+++ b/vivado-wrapper
@@ -1,9 +1,15 @@
 #!/bin/bash
 
+# TODO: Vivado create new project:
+# create_project temp_project /home/recolic/tmp/_log/temp_project -part xc7a100tcsg324-1
+# file mkdir /home/recolic/tmp/_log/temp_project/temp_project.srcs/constrs_1/new
+# close [ open /home/recolic/tmp/_log/temp_project/temp_project.srcs/constrs_1/new/constraint.xdc w ]
+# add_files -fileset constrs_1 /home/recolic/tmp/_log/temp_project/temp_project.srcs/constrs_1/new/constraint.xdc
+
 _vw_bin_name="$0"
 
-_vw_version_major="0"
-_vw_version_minor="2"
+_vw_version_major="1"
+_vw_version_minor="0"
 _vw_version="${_vw_version_major}.${_vw_version_minor}"
 
 [[ $_vw_version_major == 0 ]] && echo "Vivado wrapper is unfinished, and unable to work." && exit 11
@@ -72,6 +78,16 @@ function where_am_i () {
     where_is_him "$_my_path"
 }
 
+function naive_opt () {
+    _opt_prev=""
+    for opt in $@; do
+        [[ $_opt_prev == '--top' ]] && top_module="$opt"
+        [[ $_opt_prev == '--device' ]] && device_name="$opt"
+        [[ $_opt_prev == '--constraint' ]] && constr_path="$opt"
+        _opt_prev="$opt"
+    done
+}
+
 function import_vivadofile_impl () {
     [[ -e ./Vivadofile ]] && source ./Vivadofile && return 0
     [[ -e ./vivadofile ]] && source ./vivadofile && return 0
@@ -82,13 +98,14 @@ function import_vivadofile_impl () {
 function import_vivadofile () {
     import_vivadofile_impl
     [[ $? == 1 ]] && echo 'Vivadofile, vivadofile, VivadoFile not found.' && return 1
-    [[ -e ${vivado_exec} ]] && echo "vivado_exec '${vivado_exec}' not found." && return 1
-    [[ -x ${vivado_exec} ]] && echo "vivado_exec '${vivado_exec}' not executable." && return 1
+    [[ ! -e ${vivado_exec} ]] && echo "vivado_exec '${vivado_exec}' not found." && return 1
+    [[ ! -x ${vivado_exec} ]] && echo "vivado_exec '${vivado_exec}' not executable." && return 1
     [[ "${thread_num}" == '' ]] && thread_num=1
     [[ "${sources[*]}" == '' ]] && echo "sources not provided." && return 1
     [[ "${bit_dir}" == '' ]] && echo "bit_dir not provided." && return 1
     [[ "${top_modules[*]}" == '' ]] && echo "top_modules not provided." && return 1
     [[ "${top_module}" == '' ]] && echo "top_module not provided." && return 1
+    return 0
 }
 
 function get_constraint_of_module () {
@@ -98,18 +115,20 @@ function get_constraint_of_module () {
         _value=${_ele#*:}
         [[ ${_key} == ${_mod_name} ]] && echo -n "${_value}" && return 0
     done
-    return 1
+    echo "Error: Can not find constraint for module '$_mod_name'"
+    exit 1
 }
 
 function generate_real_project () {
-    # Create a temp real vivado project in /tmp, link all sources to it, and prepare for future usage.
+    [[ "$constr_path" == '' ]] && constr_path="$(pwd)/$(get_constraint_of_module $top_module)"
     cp -r "$my_path/template/project" "$temp_dir/"
+    _real_proj_src="$temp_dir/project/temp_project.srcs"
     for src in `echo ${sources[@]}`; do
-        _unpathed_src=`echo $src | tr '/' '_' | tr ' ' '_'`
-        ln -s "$(pwd)/$src" "$temp_dir/project/temp-project.srcs/sources_1/new/$_unpathed_src"
+        mkdir -p "$_real_proj_src/sources_1/new/$(dirname "$src")"
+        ln -s "$(pwd)/$src" "$_real_proj_src/sources_1/new/$src"
     done
-    rm "$temp_dir/project/temp-project.srcs/constrs_1/new/constraint.xdc"
-    ln -s "$constr_path" "$temp_dir/project/temp-project.srcs/constrs_1/new/constraint.xdc"
+    rm "$_real_proj_src/constrs_1/new/constraint.xdc"
+    ln -s "$constr_path" "$_real_proj_src/constrs_1/new/constraint.xdc"
     echo "real_project generated at $temp_dir"
 }
 
@@ -125,28 +144,33 @@ function do_init () {
 }
 
 function do_build () {
-    # TODO: Parse cmdline, override top_module and constr
-    constr_path="$(pwd)/$(get_constraint_of_module $top_module)"
     generate_real_project
 
-    "$my_path/gen_tcl.sh" build "$temp_dir/project/temp-project.xpr" synth_1 impl_1 write_bitstream "$top_module" $thread_num > $temp_dir/sh.tcl
+    "$my_path/gen_tcl.sh" build "$temp_dir/project/temp_project.xpr" synth_1 impl_1 write_bitstream "$top_module" $thread_num > $temp_dir/sh.tcl
     "$vivado_exec" -mode batch -source "$temp_dir/sh.tcl" -nojournal -nolog
-    _bit_file="$temp_dir/project/temp-project.runs/impl_1/$top_module.bit"
+    _bit_file="$temp_dir/project/temp_project.runs/impl_1/$top_module.bit"
     [[ -e "$_bit_file" ]] && cp "$_bit_file" "$bit_dir/$top_module.bit" || echo "vivado-wrapper: Error: Build failed."
 
     clean_real_project
 }
 
 function burn_file () {
-    # TODO: Parse cmdline to get device_name if any.
     file_to_burn="$1"
-    "$my_path/gen_tcl.sh" burn-file "$file_to_burn" > $temp_dir/sh.tcl
+    "$my_path/gen_tcl.sh" burn-file "$file_to_burn" "$device_name" > $temp_dir/sh.tcl
     "$vivado_exec" -mode batch -source "$temp_dir/sh.tcl" -nojournal -nolog
 }
 
 function do_burn () {
-    # TODO: Parse cmdline, override top_module and device_name
     burn_file "$bit_dir/$top_module.bit"
+}
+
+function do_gui () {
+    generate_real_project
+
+    "$my_path/gen_tcl.sh" gui "$temp_dir/project/temp_project.xpr" > $temp_dir/sh.tcl
+    "$vivado_exec" -mode batch -source "$temp_dir/sh.tcl" -nojournal -nolog
+
+    clean_real_project
 }
 
 my_path=`where_am_i`
@@ -161,6 +185,8 @@ if [[ $vw_cmd == 'build' ]] || [[ $vw_cmd == 'burn' ]] || [[ $vw_cmd == 'gui' ]]
     import_vivadofile
     [[ $? != 0 ]] && echo "Vivadofile error reported. Exiting..." && exit 2
 fi
+
+naive_opt $@
 
 case $vw_cmd in
     'init' )
